### ISSUE TITLE
move scene data a  level deeper

### ISSUE THREAD

**Issue by ofZach** [ofZach/dayForNightSFPC#33]
as we start to have settings files, fonts, sounds, etc, it's a bit messy to have scene folders at the root level of data.  good to make a folder called scenes, and then put these folders in scenes.  This would require changing every scene's "load(...)" if we do this but I think for keeping things clean it will help.

**Comment by chanderson0** [comment]
Fixed in https://github.com/ofZach/dayForNightSFPC/commit/bf42c5f0663e843339653f0fb40f0f5ba72d1d8d

**Comment by ofZach** [comment]
sweet !
