### ISSUE TITLE
Highlight boolean parameter changes in the code window

### ISSUE THREAD

**Issue by solon** [ofZach/dayForNightSFPC#37]
Implementation note: when calculating parameter energy, which is used to determine the brightness of the parameters in the pseudocode, changes to boolean parameters should be picked up.

**Comment by ofZach** [comment]
if it's helpful, that logic is happening here:

https://github.com/ofZach/dayForNightSFPC/blob/master/src/scenes/typographyManager.cpp#L175-L184

I'm basically looking at the strings generated here: 

https://github.com/ofZach/dayForNightSFPC/blob/master/src/scenes/typographyManager.cpp#L153-L157

and seeing if they changed...

I'm not sure if the midi system can handle booleans though, it might easier to have a int param that's either 0 or 1, and use that as a boolean?

**Comment by solon** [comment]
Thanks, I'll investigate a bit further.

**Comment by roymacdonald** [comment]
Hi, the midi implementation does handle booleans. it can be via buttons or sliders. right now, due to the auto assignation of midi to ofParameter it is using the sliders, but there is no problem with buttons.

**Comment by ofZach** [comment]
I just meant that if we want to avoid having to do mappings per scene, we could jsut keep everything as sliders, might be easier (to map slider a in gui to slider 1 on the keypad, etc)

**Comment by solon** [comment]
You can see this working now in `mgsCooperSymbols` by toggling the `Random Colored Stroke` checkbox.
