### ISSUE TITLE
please clarify variable name

### ISSUE THREAD

**Issue by chanderson0** [ofZach/dayForNightSFPC#42]
@sarahgp we in houston were wondering whether the `weeArc` variable in your sketch means "wee" like small or "wee" like "weeee i'm on a roller coaster". please let us know   👻

**Comment by sarahghp** [comment]
Oooo. Definitely the former. The latter has an _h_. :mouse: :roller_coaster:

**Comment by chanderson0** [comment]
👍👍👍👍👍
