### ISSUE TITLE
XCode Settings for includes

### ISSUE THREAD

**Issue by AnnaMag** [ofZach/dayForNightSFPC#48]
the link is not working:)

**Comment by ofZach** [comment]
sorry what does this mean?

**Comment by AnnaMag** [comment]
there is a link in the Readme.md in section 4: Xcode settings. As is, is not compiling for me (does not shave access to the OF native libs)

**Comment by ofZach** [comment]
sorry it's a missing image. 

do you have the day for night folder in the right place in openframeworks?  are you using 0.9 ?

**Comment by AnnaMag** [comment]
my bad- the d4night directory was 1 level too low. Sorry- all is working great!
