### ISSUE TITLE
midi controller?

### ISSUE THREAD

**Issue by ofZach** [ofZach/dayForNightSFPC#6]
seems like a midi controller would be an ideal way to alter these parameters.  Try hooking up the korg nano controller to this....

**Comment by roymacdonald** [comment]
I have some stuff made to hookup midi to ofParameters and link them just by moving both the guislider and the the midi controller, when the learn mode is active. I'll include it and PR. It would be nice to have a kind of custom made controller with big knobs and nice light rings. I would be more than happy to make it. Do we have any kind of budget for such thing?

**Comment by ofZach** [comment]
I don't know if we will use a device live at the event.  My overall feeling is that it's ok it's not interactive and we don't have to kill ourselves with custom devices. 

I think even just recording params and giving a scene a kind of loop might be nice and good for the scene to show itself off.  I was just going to map korg nano sliders to the param group each scene provides...

**Comment by roymacdonald** [comment]
Ohh I thought that we were going to have a device for the users/audience.
I have that thing made for learning the params. It´s super straigth forwards. Im working on it right now.

**Comment by ofZach** [comment]
I am trying to make sure we focus on the art not the tools :)  and have a good time in houston.   I think if the piece is more like a movie but super strong it's better then if it's interactive but we don't have enough content....  I think it's hard for example, to know how many params each scene might need, and it's kind of cool to have it more like a movie that we perform / record and just loop back to people....

**Comment by ofZach** [comment]
(also just trying to be a bit conservative, it feels like a harder place to build interactive things for than most contexts)

**Comment by ofZach** [comment]
(finally, i think we could build in a kind of override to the param playback, then demo for people using a korg nano on site....   ie, interactive for curious audiences)

**Comment by roymacdonald** [comment]
Sure. Completely agree with content over tools approach. I made this thing I´m telling for using it live and being able to leave some parameters "looped" while tweaking others. So the demo for curious ones is already built in :)

**Comment by ofZach** [comment]
midi has been hooked up, closing!
